version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-students
    ports:
      - '6520:5432'
    volumes:
      - postgresStudentsDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis-students
    ports:
      - '6409:6379'
    volumes:
      - redisStudentsDB:/data
volumes:
  postgresStudentsDB:
  redisStudentsDB:
